// Mocks generated by Mockito 5.4.6 from annotations
// in doublevpartners/test/mocks/address_list_view_test.mocks.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:doublevpartners/dao/adapter_dao.dart' as _i3;
import 'package:doublevpartners/db/entities/user_entity.dart' as _i2;
import 'package:doublevpartners/modules/user/controller/user_controller.dart'
    as _i4;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeUserDao_0 extends _i1.SmartFake implements _i2.UserDao {
  _FakeUserDao_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeAdapterDao_1 extends _i1.SmartFake implements _i3.AdapterDao {
  _FakeAdapterDao_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [UserController].
///
/// See the documentation for Mockito's code generation for more information.
class MockUserController extends _i1.Mock implements _i4.UserController {
  MockUserController() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.UserDao get userDao =>
      (super.noSuchMethod(
            Invocation.getter(#userDao),
            returnValue: _FakeUserDao_0(this, Invocation.getter(#userDao)),
          )
          as _i2.UserDao);

  @override
  _i3.AdapterDao get adapterDao =>
      (super.noSuchMethod(
            Invocation.getter(#adapterDao),
            returnValue: _FakeAdapterDao_1(
              this,
              Invocation.getter(#adapterDao),
            ),
          )
          as _i3.AdapterDao);

  @override
  _i5.Future<int> insertUser({
    required String? name,
    required String? lastName,
    required String? birthdate,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#insertUser, [], {
              #name: name,
              #lastName: lastName,
              #birthdate: birthdate,
            }),
            returnValue: _i5.Future<int>.value(0),
          )
          as _i5.Future<int>);

  @override
  _i5.Future<int> insertAddress({
    required int? userId,
    required String? street,
    required String? city,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#insertAddress, [], {
              #userId: userId,
              #street: street,
              #city: city,
            }),
            returnValue: _i5.Future<int>.value(0),
          )
          as _i5.Future<int>);

  @override
  _i5.Future<void> insertMultipleAddresses({
    required int? userId,
    required List<Map<String, String>>? addresses,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#insertMultipleAddresses, [], {
              #userId: userId,
              #addresses: addresses,
            }),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<List<Map<String, dynamic>>> getAddressesByUserId(int? userId) =>
      (super.noSuchMethod(
            Invocation.method(#getAddressesByUserId, [userId]),
            returnValue: _i5.Future<List<Map<String, dynamic>>>.value(
              <Map<String, dynamic>>[],
            ),
          )
          as _i5.Future<List<Map<String, dynamic>>>);

  @override
  _i5.Future<List<Map<String, dynamic>>> getAllUsers() =>
      (super.noSuchMethod(
            Invocation.method(#getAllUsers, []),
            returnValue: _i5.Future<List<Map<String, dynamic>>>.value(
              <Map<String, dynamic>>[],
            ),
          )
          as _i5.Future<List<Map<String, dynamic>>>);
}
